[package]
name = "wasmtime-test"
version = "0.1.0"
edition = "2018"


[dependencies]
wasmtime="0.13.0"
wasmtime-wasi="0.13.0"
wasi-common="0.13.0"
anyhow="1.0.27"
binio = { path ="../binio"}
serde = { version = "1.0", features = ["derive"] }
[features]
default=[]
verbose=[]