[package]
name = "web"
version = "0.1.0"
authors = ["yz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1"

wasmer-runtime = "0.14.1"
wasmer-middleware-common = "0.14.1"
wasmer-runtime-core = "0.14.1"
wasmer-singlepass-backend = "0.14.1"

tonic = "0.1.1"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }

